apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-new
spec:
  replicas: 2
  selector:
    matchLabels:
      app: resume-new
  template:
    metadata:
      labels:
        app: resume-new
    spec:
      containers:
      - name: resume-new
        image: 010928195739.dkr.ecr.ap-southeast-2.amazonaws.com/resume-new/resume-new:IMAGE_TAG_PLACEHOLDER
        ports:
        - containerPort: 80