name: Docker Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs: 
  docker_build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/new-app:latest .

      - name: Docker Publish
        run: docker push ${{ secrets.DOCKER_USERNAME }}/new-app:latest

  docker_deploy:
    needs: docker_build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Run
        run: |
         docker run -d -p 8080:80 ${{ secrets.DOCKER_USERNAME }}/new-app:latest
         sleep 300s