name: Docker Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker_build:
    runs-on: ubuntu-latest
    env:
      CONTAINER_REGISTRY: docker.io
      IMAGE_NAME: srj-app

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Docker Build
        run: docker build -t ${{ env.CONTAINER_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest .

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Publish code to DockerHub
        run: docker push ${{ env.CONTAINER_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest

      - name: GHCR Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PATH }}

      - name: Publish code to GHCR
        run: |
          docker build -t ghcr.io/haiyuecheng/${{ env.IMAGE_NAME }}:latest .
          docker push ghcr.io/haiyuecheng/${{ env.IMAGE_NAME }}:latest
