name: Matrix Configuration

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    strategy:
      fail-fast: false # when a job fails, it will not affect successive jobs running in parallel.
      max-parallel: 3
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, windows-latest]
        image: [hello-world,nginx,node,python, alpine]
        exclude:
          - os: windows-latest
            image: alpine
          - os: ubuntu-20.04
            image: alpine
    runs-on: ${{ matrix.os }}
    env:
      ENVIRONMENT: staging
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Echo Docker Details
        run: docker info

      - name: Run Image on ${{ matrix.os }}
        run: docker run ${{ matrix.image }}
